### ISSUE TITLE
Sections are not integrated in section pane left side

### ISSUE THREAD

**Issue by sukunis** [ome/omero-guide-mde#1]
@jburel  Sections and subsections of OMERO.mde guide are not integrated in the section menue of OMERO guides.

**Comment by jburel** [comment]
* sections and subsections should now be visible
* Fixed layout and formatting

**Comment by sukunis** [comment]
I've tried with two different browser, but the subsections of OMERO.mde are not visible on the left section pane. Therefore it is hard to navigate through the guide. If the integration in the menu pane is not possible, I would integrate previous and next buttons for navigations.

**Comment by jburel** [comment]
We can change the limit on the toc. This is what is currently published.
<img width="529" alt="Screenshot 2020-05-04 at 08 19 35" src="https://user-images.githubusercontent.com/1022396/80943841-07b95a80-8de0-11ea-9838-4a6a47d62a22.png">

**Comment by jburel** [comment]
What do you want to have?

**Comment by sukunis** [comment]
Like for the other Add-Ons:
![Issue_MenuPane](https://user-images.githubusercontent.com/29231744/80946442-5c63d200-8dee-11ea-9711-385debf488a3.png)

**Comment by jburel** [comment]
I see
I need to check what happens when I added it something is not correct

**Comment by jburel** [comment]
This should be fixed and doc available

<img width="529" alt="Screenshot 2020-05-04 at 11 13 43" src="https://user-images.githubusercontent.com/1022396/80956146-84f0c980-8df8-11ea-8ea9-39d95f4d71ca.png">

**Comment by joshmoore** [comment]
@jburel : what change was needed in case this happens again?

**Comment by jburel** [comment]
toc needed to be included correctly and I have now included html_configuration for the sphinx theme used by readthedocs

**Comment by joshmoore** [comment]
i.e. https://github.com/ome/omero-guide-mde/commit/ee8f3b92f90475f149ec7ad4cc1486081d273697 ?

**Comment by jburel** [comment]
For the record https://github.com/ome/omero-guides/commit/f5616fa81699b5357fd92e81b62f66728b86adda
and 
https://github.com/ome/omero-guides/commit/9cc222614929f33c9fae5a5728e69490647ccd9c
